### ISSUE TITLE
scimax-split-src-block not working

### ISSUE THREAD

**Issue by peteWT** [jkitchin/scimax#405]
Hi,

`M-x` does not find `org-babel-split-src-block`. I've updated scimax. When I use the menu bar with cursor in source block to split the source block I get the error:

`command-execute: Wrong type argument: commandp, scimax-split-src-block`

Thanks for any insights.

**Comment by jkitchin** [comment]
Those are my fault, I refactored these and forgot to update these. I have pushed a fix for these. Thanks for reporting.

**Comment by peteWT** [comment]
Thank you sir! I can now use the menu bar version. Can you let me know how to enable the key bindings for that. Also, I still cant see `M-x org-babel-split-source-block` or `M-x scimax-split-source-block`

**Comment by jkitchin** [comment]
Neither of those commands exist anymore, where did you find them? see the variable `ob-ipython-key-bindings` for what these are bound to.
